fit:
  trainer:
    max_epochs: 100
    accelerator: cuda
    devices: 1
  data:
    dataset_name: losloop
    batch_size: 64
    seq_len: 12
    pre_len: 1
  model:
    model:
      class_path: models.GCN
      init_args:
        hidden_dim: 100
        use_gsl: true
    learning_rate: 0.001
    weight_decay: 0
    loss: mse
